/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MasottiDeveloper;

import org.joda.time.LocalTime;

import for_gradle_proj.Student;
import masotti_2.Provider;
import mosotti_1.Service;

public class App {
	
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		Student student = new Student();
		student.sayStudent();
		Service service = new Service();
		service.helloFromService();
		Provider provider = new Provider();
		provider.sayHelloFromProvider();
		LocalTime currentTime = new LocalTime();
		System.out.println("The current local time is: " + currentTime);

		System.out.println(new App().getGreeting());
	}
}
